// Comprehensive mapping of countries to their major regions/areas
export const COUNTRIES_REGIONS: Record<string, string[]> = {
  'United States': [
    'New York',
    'California',
    'Florida',
    'Texas',
    'Colorado',
    'Hawaii',
    'Washington',
    'Massachusetts',
    'Illinois',
    'Louisiana',
  ],
  'United Kingdom': [
    'London',
    'England',
    'Scotland',
    'Wales',
    'Northern Ireland',
  ],
  France: [
    'Paris',
    'Provence',
    'Côte d\'Azur',
    'Normandy',
    'Loire Valley',
    'Alsace',
    'Bordeaux',
  ],
  Germany: [
    'Berlin',
    'Bavaria',
    'Rhine Valley',
    'Hamburg',
    'Munich',
    'Frankfurt',
  ],
  Spain: [
    'Madrid',
    'Barcelona',
    'Andalusia',
    'Valencia',
    'Basque Country',
    'Catalonia',
  ],
  Italy: [
    'Rome',
    'Milan',
    'Venice',
    'Florence',
    'Naples',
    'Sicily',
    'Tuscany',
  ],
  Japan: [
    'Tokyo',
    'Kyoto',
    'Osaka',
    'Hokkaido',
    'Hiroshima',
    'Nagano',
    'Mount Fuji',
    'Yokohama',
  ],
  Thailand: [
    'Bangkok',
    'Chiang Mai',
    'Phuket',
    'Krabi',
    'Pattaya',
    'Koh Samui',
    'Isaan',
  ],
  Vietnam: [
    'Hanoi',
    'Ho Chi Minh City',
    'Ha Long Bay',
    'Da Nang',
    'Sapa',
    'Hoi An',
    'Mekong Delta',
  ],
  India: [
    'New Delhi',
    'Mumbai',
    'Goa',
    'Rajasthan',
    'Kerala',
    'Agra',
    'Bangalore',
  ],
  Australia: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Great Barrier Reef',
    'Tasmania',
  ],
  Canada: [
    'Toronto',
    'Vancouver',
    'Banff',
    'Montreal',
    'Calgary',
    'Niagara Falls',
  ],
  Mexico: [
    'Mexico City',
    'Cancun',
    'Playa del Carmen',
    'Puerto Vallarta',
    'Los Cabos',
    'Oaxaca',
  ],
  Brazil: [
    'Rio de Janeiro',
    'São Paulo',
    'Salvador',
    'Manaus',
    'Paraná',
  ],
  'South Korea': [
    'Seoul',
    'Busan',
    'Jeju',
    'Incheon',
    'Daegu',
  ],
  Singapore: [
    'Central Singapore',
    'East Singapore',
    'North Singapore',
    'West Singapore',
  ],
  Malaysia: [
    'Kuala Lumpur',
    'Penang',
    'Sabah',
    'Sarawak',
    'Selangor',
  ],
  Indonesia: [
    'Jakarta',
    'Bali',
    'Yogyakarta',
    'Lombok',
    'Sumatra',
  ],
  Philippines: [
    'Manila',
    'Cebu',
    'Davao',
    'Palawan',
    'Boracay',
  ],
  Turkey: [
    'Istanbul',
    'Ankara',
    'Antalya',
    'Cappadocia',
    'Izmir',
  ],
  Greece: [
    'Athens',
    'Crete',
    'Santorini',
    'Mykonos',
    'Rhodes',
  ],
  Portugal: [
    'Lisbon',
    'Porto',
    'Algarve',
    'Madeira',
    'Sintra',
  ],
  Netherlands: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Groningen',
  ],
  Belgium: [
    'Brussels',
    'Bruges',
    'Antwerp',
    'Ghent',
  ],
  Switzerland: [
    'Zurich',
    'Geneva',
    'Bern',
    'Interlaken',
    'Lucerne',
  ],
  Austria: [
    'Vienna',
    'Salzburg',
    'Innsbruck',
    'Graz',
  ],
  'Czech Republic': [
    'Prague',
    'Brno',
    'Český Krumlov',
    'Carlsbad',
  ],
  Poland: [
    'Warsaw',
    'Krakow',
    'Gdansk',
    'Wroclaw',
  ],
  Sweden: [
    'Stockholm',
    'Gothenburg',
    'Malmö',
    'Uppsala',
  ],
  Norway: [
    'Oslo',
    'Bergen',
    'Tromsø',
    'Lillehammer',
  ],
  Denmark: [
    'Copenhagen',
    'Aarhus',
    'Odense',
  ],
  'New Zealand': [
    'Auckland',
    'Wellington',
    'Christchurch',
    'Queenstown',
    'Rotorua',
  ],
  'South Africa': [
    'Cape Town',
    'Johannesburg',
    'Durban',
    'Kruguer National Park',
  ],
  Egypt: [
    'Cairo',
    'Giza',
    'Luxor',
    'Aswan',
    'Alexandria',
  ],
  Morocco: [
    'Marrakech',
    'Fez',
    'Casablanca',
    'Essaouira',
    'Agadir',
  ],
  Kenya: [
    'Nairobi',
    'Mombasa',
    'Masai Mara',
    'Amboseli',
  ],
  UAE: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ras Al Khaimah',
  ],
  'Saudi Arabia': [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
  ],
  China: [
    'Beijing',
    'Shanghai',
    'Xi\'an',
    'Chengdu',
    'Guangzhou',
    'Hangzhou',
  ],
  'Hong Kong': [
    'Central',
    'Kowloon',
    'New Territories',
    'Victoria Peak',
  ],
  Taiwan: [
    'Taipei',
    'Taichung',
    'Kaohsiung',
    'Tainan',
  ],
  Pakistan: [
    'Islamabad',
    'Lahore',
    'Karachi',
    'Peshawar',
  ],
  Bangladesh: [
    'Dhaka',
    'Chittagong',
    'Sylhet',
    'Khulna',
  ],
  'Sri Lanka': [
    'Colombo',
    'Kandy',
    'Galle',
    'Nuwara Eliya',
  ],
  Nepal: [
    'Kathmandu',
    'Pokhara',
    'Everest Base Camp',
    'Chitwan',
  ],
  Cambodia: [
    'Phnom Penh',
    'Siem Reap',
    'Sihanoukville',
    'Battambang',
  ],
  Laos: [
    'Vientiane',
    'Luang Prabang',
    'Pakse',
    'Vang Vieng',
  ],
  Myanmar: [
    'Yangon',
    'Mandalay',
    'Bagan',
    'Inle Lake',
  ],
  Afghanistan: [
    'Kabul',
    'Kandahar',
    'Herat',
    'Jalalabad',
  ],
  Iran: [
    'Tehran',
    'Isfahan',
    'Shiraz',
    'Mashhad',
  ],
  Israel: [
    'Tel Aviv',
    'Jerusalem',
    'Haifa',
    'Dead Sea',
  ],
  Jordan: [
    'Amman',
    'Petra',
    'Dead Sea',
    'Jerash',
  ],
  Lebanon: [
    'Beirut',
    'Baalbek',
    'Byblos',
    'Sidon',
  ],
  Cyprus: [
    'Nicosia',
    'Limassol',
    'Paphos',
    'Larnaca',
  ],
  Malta: [
    'Valletta',
    'Sliema',
    'Mdina',
    'Gozo',
  ],
  Iceland: [
    'Reykjavik',
    'Akureyri',
    'Vik',
    'Golden Circle',
  ],
  Ireland: [
    'Dublin',
    'Cork',
    'Galway',
    'Limerick',
  ],
  Scotland: [
    'Edinburgh',
    'Glasgow',
    'Inverness',
    'Isle of Skye',
  ],
  Wales: [
    'Cardiff',
    'Swansea',
    'Snowdonia',
    'Conwy',
  ],
  Croatia: [
    'Zagreb',
    'Dubrovnik',
    'Split',
    'Dalmatia',
  ],
  Serbia: [
    'Belgrade',
    'Nis',
    'Novi Sad',
  ],
  Romania: [
    'Bucharest',
    'Brasov',
    'Transylvania',
    'Constanta',
  ],
  Bulgaria: [
    'Sofia',
    'Plovdiv',
    'Varna',
    'Black Sea Coast',
  ],
  Hungary: [
    'Budapest',
    'Debrecen',
    'Szeged',
    'Lake Balaton',
  ],
  Slovakia: [
    'Bratislava',
    'Kosice',
    'High Tatras',
  ],
  Slovenia: [
    'Ljubljana',
    'Lake Bled',
    'Lake Bohinj',
    'Postojna',
  ],
  Ukraine: [
    'Kyiv',
    'Lviv',
    'Odesa',
    'Kharkiv',
  ],
  Russia: [
    'Moscow',
    'St. Petersburg',
    'Sochi',
    'Yekaterinburg',
  ],
  Belarus: [
    'Minsk',
    'Brest',
    'Vitebsk',
    'Grodno',
  ],
  Kazakhstan: [
    'Almaty',
    'Astana',
    'Karaganda',
    'Shymkent',
  ],
  Uzbekistan: [
    'Tashkent',
    'Samarkand',
    'Bukhara',
    'Khiva',
  ],
  Georgia: [
    'Tbilisi',
    'Batumi',
    'Gori',
    'Kutaisi',
  ],
  Armenia: [
    'Yerevan',
    'Gyumri',
    'Gavar',
  ],
  Azerbaijan: [
    'Baku',
    'Ganja',
    'Sheki',
    'Nakhchivan',
  ],
  Peru: [
    'Lima',
    'Machu Picchu',
    'Cusco',
    'Sacred Valley',
    'Arequipa',
  ],
  Ecuador: [
    'Quito',
    'Galápagos Islands',
    'Amazon',
    'Cuenca',
  ],
  Colombia: [
    'Bogotá',
    'Cartagena',
    'Medellín',
    'Santa Marta',
  ],
  Venezuela: [
    'Caracas',
    'Los Roques',
    'Margarita Island',
  ],
  Argentina: [
    'Buenos Aires',
    'Mendoza',
    'Bariloche',
    'Salta',
  ],
  Chile: [
    'Santiago',
    'Atacama Desert',
    'Patagonia',
    'Easter Island',
  ],
  Bolivia: [
    'La Paz',
    'Salt Flats',
    'Santa Cruz',
  ],
  Paraguay: [
    'Asunción',
    'Iguazu Falls',
  ],
  Uruguay: [
    'Montevideo',
    'Punta del Este',
    'Colonia',
  ],
  'Costa Rica': [
    'San José',
    'La Fortuna',
    'Manuel Antonio',
    'Arenal',
  ],
  Panama: [
    'Panama City',
    'Bocas del Toro',
    'San Blas Islands',
    'Boquete',
  ],
  Jamaica: [
    'Kingston',
    'Montego Bay',
    'Negril',
    'Ocho Rios',
  ],
  Cuba: [
    'Havana',
    'Trinidad',
    'Varadero',
    'Santiago',
  ],
  'Dominican Republic': [
    'Santo Domingo',
    'Punta Cana',
    'Puerto Plata',
  ],
  'Puerto Rico': [
    'San Juan',
    'Vieques',
    'El Yunque',
  ],
  Bahamas: [
    'Nassau',
    'Freeport',
    'Exuma',
  ],
  Belize: [
    'Belize City',
    'Ambergris Caye',
    'Placencia',
  ],
  Guatemala: [
    'Guatemala City',
    'Antigua',
    'Lake Atitlan',
  ],
  Honduras: [
    'Tegucigalpa',
    'Utila',
    'Roatan',
  ],
  'El Salvador': [
    'San Salvador',
    'Santa Ana',
  ],
  Nicaragua: [
    'Managua',
    'Granada',
    'San Juan del Sur',
  ],
  Fiji: [
    'Suva',
    'Nadi',
    'Coral Coast',
  ],
  Samoa: [
    'Apia',
    'Savai\'i',
  ],
  Tonga: [
    'Nuku\'alofa',
  ],
  Bali: [
    'Ubud',
    'Seminyak',
    'Denpasar',
    'Kuta',
  ],
  Maldives: [
    'Malé',
    'Addu Atoll',
    'Male City',
  ],
  Seychelles: [
    'Victoria',
    'Mahé',
    'Praslin',
  ],
  Mauritius: [
    'Port Louis',
    'Grand Baie',
    'Black River',
  ],
};

export const COUNTRIES = Object.keys(COUNTRIES_REGIONS);

// Helper function to get regions for a country
export const getRegionsForCountry = (country: string): string[] => {
  return COUNTRIES_REGIONS[country] || [];
};
